# Generated by Django 4.2.5 on 2023-09-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_token_itemtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("categoryId", models.AutoField(primary_key=True, serialize=False)),
                ("maxPerDay", models.IntegerField()),
                (
                    "provisionner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provisionner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qt", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.token"
                    ),
                ),
            ],
        ),
    ]
