# Generated by Django 4.2.5 on 2023-09-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_category_categorytoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tokens",
            field=models.ManyToManyField(through="api.CategoryToken", to="api.token"),
        ),
        migrations.AddField(
            model_name="token",
            name="items",
            field=models.ManyToManyField(through="api.ItemToken", to="api.item"),
        ),
    ]
